/**
 * Renders AI-generated career guidance returned by the backend `/suggest`
 * endpoint. Handles its own loading and error presentation so the parent only
 * has to pass state in.
 *
 * @param {object}  props
 * @param {boolean} props.loading        Whether suggestions are being fetched.
 * @param {string}  [props.error]        Error message, if the request failed.
 * @param {object}  [props.suggestions]  The suggestions payload.
 */
export default function AiSuggestions({ loading, error, suggestions }) {
  return (
    <section className="ai card">
      <h2 className="ai__title">
        <span aria-hidden>🤖</span> AI career guidance
      </h2>

      {loading && (
        <div className="ai__loading">
          <div className="spinner spinner--sm" aria-hidden />
          <span>Generating personalized suggestions…</span>
        </div>
      )}

      {!loading && error && <p className="alert alert--warn">{error}</p>}

      {!loading && !error && suggestions && (
        <div className="ai__body">
          {suggestions.fit_summary && (
            <p className="ai__summary">{suggestions.fit_summary}</p>
          )}

          {suggestions.strengths?.length > 0 && (
            <div className="ai__group">
              <h3 className="ai__heading">
                <span className="ai__heading-emoji" aria-hidden>
                  💪
                </span>
                Strengths
              </h3>
              <ul className="ai__list">
                {suggestions.strengths.map((s, i) => (
                  <li key={i}>{s}</li>
                ))}
              </ul>
            </div>
          )}

          {suggestions.gap_advice?.length > 0 && (
            <div className="ai__group">
              <h3 className="ai__heading">
                <span className="ai__heading-emoji" aria-hidden>
                  🎯
                </span>
                Closing the gaps
              </h3>
              <ul className="ai__list">
                {suggestions.gap_advice.map((g, i) => (
                  <li key={i}>
                    {g.skill && <strong>{g.skill}: </strong>}
                    {g.how_to_address}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {suggestions.resume_improvements?.length > 0 && (
            <div className="ai__group">
              <h3 className="ai__heading">
                <span className="ai__heading-emoji" aria-hidden>
                  📝
                </span>
                Résumé improvements
              </h3>
              <ul className="ai__list">
                {suggestions.resume_improvements.map((s, i) => (
                  <li key={i}>{s}</li>
                ))}
              </ul>
            </div>
          )}

          {suggestions.next_steps?.length > 0 && (
            <div className="ai__group">
              <h3 className="ai__heading">
                <span className="ai__heading-emoji" aria-hidden>
                  🚀
                </span>
                Next steps
              </h3>
              <ol className="ai__list ai__list--ordered">
                {suggestions.next_steps.map((s, i) => (
                  <li key={i}>{s}</li>
                ))}
              </ol>
            </div>
          )}

          {suggestions.model && (
            <p className="ai__meta">Generated by {suggestions.model} via OpenRouter</p>
          )}
        </div>
      )}
    </section>
  );
}
